config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'measurements/index'
  get 'measurements/import'
  get 'measurements/table_page' => 'measurements#table_page'
  get '/measurements/humidity_heatmap' => 'measurements#humidity_heatmap'
  get '/measurements/air_humidity_heatmap' => 'measurements#air_humidity_heatmap'
  get '/measurements/air_temperature_heatmap' => 'measurements#air_temperature_heatmap'


  match 'manual(/:action)', controller: 'manual', via: :all
  resources :measurements do
    collection { post :import }
  end

  match 'settings(/:action)', controller: 'settings', via: :all
  match 'net(/:action)', controller: 'sockets', via: :all

end

app/models/measurement.rb
class Measurement < ApplicationRecord
  require 'smarter_csv'

  def self.import(file)

    Measurement.delete_all

    SmarterCSV.process('public/measurements/03121995_235423.csv', headers_in_file: false, user_provided_headers: %i[started_at gathering_time gathering_date latitude longitude absolute_humidity air_humidity air_temperature]) do |chunk|
      chunk.each do |data_hash|
        Measurement.create!( data_hash )
      end
    end

  end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  def index
    @measurements = Measurement.all.map(&:started_at).uniq
  end

  def table_page
    @measurements = Measurement.where(started_at: params[:id])
  end

  def import
    Measurement.import(params[:file])
    redirect_to measurements_url
  end

  def humidity_heatmap
    @measurements = Measurement.where(started_at: params[:id])

    latitude_array = []
    longitude_array = []
    humidity_array = []

    @measurements.each_with_index do |measurement, humidity_heatmap|
      latitude_array.append(measurement.latitude)
      longitude_array.append(measurement.longitude)
      humidity_array.append(measurement.absolute_humidity)
    end

    @js_lat = latitude_array
    @js_long = longitude_array
    @js_humidity = humidity_array
  end

  def air_humidity_heatmap
    @measurements = Measurement.where(started_at: params[:id])

    latitude_array = []
    longitude_array = []
    air_humidity_array = []

    @measurements.each_with_index do |measurement, air_humidity_heatmap|
      latitude_array.append(measurement.latitude)
      longitude_array.append(measurement.longitude)
      air_humidity_array.append(measurement.air_humidity)
    end

    @js_lat = latitude_array
    @js_long = longitude_array
    @js_air_humidity = air_humidity_array
  end

  def air_temperature_heatmap
    @measurements = Measurement.where(started_at: params[:id])

    latitude_array = []
    longitude_array = []
    air_temperature_array = []

    @measurements.each_with_index do |measurement, air_temperature_heatmap|
      latitude_array.append(measurement.latitude)
      longitude_array.append(measurement.longitude)
      air_temperature_array.append(measurement.air_temperature)
    end

    @js_lat = latitude_array
    @js_long = longitude_array
    @js_air_temperature = air_temperature_array
  end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/air_humidity_heatmap.html.erb
<!DOCTYPE html>
<html>

<style>
  #titulo {
    padding-left: 5%;
    padding-right: 5%;
  }
  #botao {
    padding-left: 90%;
  }
</style>

  <div class="content measurements">
    <div id="titulo">
      <h4>
        <i class="material-icons prefix"></i>
        <span>Pontos de Umidade do Ar || Mapa de Calor</span>
      </h4>
    </div>
  </div>

  <head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="style.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script src="http://www.w3schools.com/lib/w3data.js"></script>

    <style>
      #map {
        height: 100%;
        margin-left: 5%;
        margin-right: 5%;
        margin-bottom: 1%;
      }
      html {
        height: 100%;
        /*margin-left: 10%;*/
        padding: 0;
      }
      body {
        height: 75%;
        margin: 0;
        padding: 0;
      }
    </style>

  </head>

  <body>
    <div id="map"></div>
  </body>

  <div id="botao">
    <%= link_to "Voltar", measurements_path, class: 'btn btn-default' %>
  </div>

  <script>

    var map, heatmap;

    function initMap() {

      var i = 0;
      var js_lat = [];
      var js_long = [];
      var js_air_humidity = [];
      var coordinates = [];
      var coordinates_weighted = [];

      var gradient = [
       'rgba(0, 255, 255, 0)',
       'rgba(0, 255, 255, 1)',
       'rgba(0, 191, 255, 1)',
       'rgba(0, 127, 255, 1)',
       'rgba(0, 63, 255, 1)',
       'rgba(0, 0, 255, 1)',
       'rgba(0, 0, 223, 1)',
       'rgba(0, 0, 191, 1)',
       'rgba(0, 0, 159, 1)',
       'rgba(0, 0, 127, 1)',
       'rgba(63, 0, 91, 1)',
       'rgba(127, 0, 63, 1)',
       'rgba(191, 0, 31, 1)',
       'rgba(255, 0, 0, 1)'
     ]

      js_lat = <%= @js_lat %>;
      for (i = 0; i < js_lat.length ; i++){
        js_lat[i] = <%= @js_lat %>[i];
        js_long[i] = <%= @js_long %>[i];
        js_air_humidity[i] = <%= @js_air_humidity %>[i];

        coordinates[i] = new google.maps.LatLng(js_lat[i], js_long[i]);
        coordinates_weighted[i] = {location: coordinates[i], weight: js_air_humidity[i]};
      }

      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 21,
        center: {lat: js_lat[0], lng: js_long[0]},
        disableDefaultUI: true,
        zoomControl: true,
        mapTypeId: 'satellite',

      });

      heatmap = new google.maps.visualization.HeatmapLayer({
        data: coordinates_weighted,
        map: map,
        radius: 25,
        opacity: 1
      });

      heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
    }


  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCuUKw5Dpn72KHksmdOvPHKA6PVfo2jVhc&libraries=visualization&callback=initMap">
  </script>

app/views/measurements/air_temperature_heatmap.html.erb
<!DOCTYPE html>
<html>

<style>
  #titulo {
    padding-left: 5%;
    padding-right: 5%;
  }
  #botao {
    padding-left: 90%;
  }
</style>

  <div class="content measurements">
    <div id="titulo">
      <h4>
        <i class="material-icons prefix"></i>
        <span>Pontos de Temperatura do Ar || Mapa de Calor</span>
      </h4>
    </div>
  </div>

  <head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="style.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script src="http://www.w3schools.com/lib/w3data.js"></script>

    <style>
      #map {
        height: 100%;
        margin-left: 5%;
        margin-right: 5%;
        margin-bottom: 1%;
      }
      html {
        height: 100%;
        /*margin-left: 10%;*/
        padding: 0;
      }
      body {
        height: 75%;
        margin: 0;
        padding: 0;
      }
    </style>

  </head>

  <body>
    <div id="map"></div>
  </body>

  <div id="botao">
    <%= link_to "Voltar", measurements_path, class: 'btn btn-default' %>
  </div>

  <script>

    var map, heatmap;

    function initMap() {

      var i = 0;
      var js_lat = [];
      var js_long = [];
      var js_air_temperature = [];
      var coordinates = [];
      var coordinates_weighted = [];

      var gradient = [
       'rgba(0, 255, 255, 0)',
       'rgba(0, 255, 255, 1)',
       'rgba(0, 191, 255, 1)',
       'rgba(0, 127, 255, 1)',
       'rgba(0, 63, 255, 1)',
       'rgba(0, 0, 255, 1)',
       'rgba(0, 0, 223, 1)',
       'rgba(0, 0, 191, 1)',
       'rgba(0, 0, 159, 1)',
       'rgba(0, 0, 127, 1)',
       'rgba(63, 0, 91, 1)',
       'rgba(127, 0, 63, 1)',
       'rgba(191, 0, 31, 1)',
       'rgba(255, 0, 0, 1)'
     ]

      js_lat = <%= @js_lat %>;
      for (i = 0; i < js_lat.length ; i++){
        js_lat[i] = <%= @js_lat %>[i];
        js_long[i] = <%= @js_long %>[i];
        js_air_temperature[i] = <%= @js_air_temperature %>[i];

        coordinates[i] = new google.maps.LatLng(js_lat[i], js_long[i]);
        coordinates_weighted[i] = {location: coordinates[i], weight: js_air_temperature[i]};
      }

      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 21,
        center: {lat: js_lat[0], lng: js_long[0]},
        disableDefaultUI: true,
        zoomControl: true,
        mapTypeId: 'satellite',

      });

      heatmap = new google.maps.visualization.HeatmapLayer({
        data: coordinates_weighted,
        map: map,
        radius: 25,
        opacity: 1
      });

      // heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
    }


  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCuUKw5Dpn72KHksmdOvPHKA6PVfo2jVhc&libraries=visualization&callback=initMap">
  </script>

app/views/measurements/humidity_heatmap.html.erb
<!DOCTYPE html>
<html>

<style>
  #titulo {
    padding-left: 5%;
    padding-right: 5%;
  }
  #botao {
    padding-left: 90%;
  }
</style>

  <div class="content measurements">
    <div id="titulo">
      <h4>
        <i class="material-icons prefix"></i>
        <span>Pontos de Umidade do Solo || Mapa de Calor</span>
      </h4>
    </div>
  </div>

  <head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="style.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script src="http://www.w3schools.com/lib/w3data.js"></script>

    <style>
      #map {
        height: 100%;
        margin-left: 5%;
        margin-right: 5%;
        margin-bottom: 1%;
      }
      html {
        height: 100%;
        /*margin-left: 10%;*/
        padding: 0;
      }
      body {
        height: 75%;
        margin: 0;
        padding: 0;
      }
    </style>

  </head>

  <body>
    <div id="map"></div>
  </body>

  <div id="botao">
    <%= link_to "Voltar", measurements_path, class: 'btn btn-default' %>
  </div>

  <script>

    var map, heatmap;

    function initMap() {

      var i = 0;
      var js_lat = [];
      var js_long = [];
      var js_humidity = [];
      var coordinates = [];
      var coordinates_weighted = [];

      var gradient = [
       'rgba(0, 255, 255, 0)',
       'rgba(0, 255, 255, 1)',
       'rgba(0, 191, 255, 1)',
       'rgba(0, 127, 255, 1)',
       'rgba(0, 63, 255, 1)',
       'rgba(0, 0, 255, 1)',
       'rgba(0, 0, 223, 1)',
       'rgba(0, 0, 191, 1)',
       'rgba(0, 0, 159, 1)',
       'rgba(0, 0, 127, 1)',
       'rgba(63, 0, 91, 1)',
       'rgba(127, 0, 63, 1)',
       'rgba(191, 0, 31, 1)',
       'rgba(255, 0, 0, 1)'
     ]

      js_lat = <%= @js_lat %>;
      for (i = 0; i < js_lat.length ; i++){
        js_lat[i] = <%= @js_lat %>[i];
        js_long[i] = <%= @js_long %>[i];
        js_humidity[i] = <%= @js_humidity %>[i];

        coordinates[i] = new google.maps.LatLng(js_lat[i], js_long[i]);
        coordinates_weighted[i] = {location: coordinates[i], weight: js_humidity[i]};
      }

      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 21,
        center: {lat: js_lat[0], lng: js_long[0]},
        disableDefaultUI: true,
        zoomControl: true,
        mapTypeId: 'satellite',

      });

      heatmap = new google.maps.visualization.HeatmapLayer({
        data: coordinates_weighted,
        map: map,
        radius: 25,
        opacity: 1
      });

      heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
    }


  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCuUKw5Dpn72KHksmdOvPHKA6PVfo2jVhc&libraries=visualization&callback=initMap">
  </script>

app/views/measurements/import.html.erb
<h1>Measurements#import</h1>
<p>Find me in app/views/measurements/import.html.erb</p>

app/views/measurements/index.html.erb
<html>

  <h1>
    <%= @filename %>
  </h1>

  <style>
    #titulo {
      padding-left: 10%;
      padding-right: 10%;
    }
    #tabela {
      padding-left: 10%;
      padding-right: 10%;
    }
    #botao {
      padding-left: 10%;
      padding-right: 10%;
    }
    #botao2 {
      padding-left: 10%;
    }
  </style>

  <div class="content measurements">

  <div id="titulo">
    <h4>
      <i class="material-icons prefix">assessment</i>
      <span>Medições</span>
    </h4>
  </div>

  <div id="botao">
    <%= form_tag import_measurements_path, multipart: true, id: 'myForm' do %>
    <% end %>

    <a id="read_data" class="waves-effect waves-light btn">Ler dados</a>


    <script>
      $(document).ready(function() {
        $('#read_data').on('click', function() { $('#myForm').submit(); });
      });

    </script>
  </div>

  <br>

  <div id="tabela">
    <table class="centered">
    <thead>
       <tr>
           <th>Coleta</th>
           <th>Tabela</th>
           <th>Mapa de Calor</th>
           <th>Mapa de Calor</th>
           <th>Mapa de Calor</th>
       </tr>
    </thead>

    <tbody>
      <% @measurements.each_with_index do |measurement, index| %>
        <tr>
          <td><%= measurement %></td>
          <td><%= link_to "Tabela geral", measurements_table_page_path(:id => measurement), class: "btn waves-effect waves-light" %></td>
          <td><%= link_to "Umidade do solo", measurements_humidity_heatmap_path(:id => measurement), class: "btn waves-effect waves-light blue" %></td>
          <td><%= link_to "Umidade do ar", measurements_air_humidity_heatmap_path(:id => measurement), class: "btn waves-effect waves-light blue" %></td>
          <td><%= link_to "Temperatura do ar", measurements_air_temperature_heatmap_path(:id => measurement), class: "btn waves-effect waves-light red" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

</html>

app/views/measurements/table_page.html.erb
<html>

  <style>
    #titulo {
      padding-left: 10%;
      padding-right: 10%;
    }
    #tabela {
      padding-left: 10%;
      padding-right: 10%;
    }
    #botao {
      padding-top: 4.9%;
      padding-left: 90%;
    }
  </style>

  <div class="content measurements">

  <div id="titulo">
    <h4>
      <i class="material-icons prefix">assessment</i>
      <span>Medições</span>
    </h4>
  </div>

  <div id="tabela">
    <table class="centered">
    <thead>
       <tr>
           <th>Horário</th>
           <th>Dia</th>
           <th>Latitude</th>
           <th>Longitude</th>
           <th>Umidade do solo</th>
           <th>Umidade do ar</th>
           <th>Temperatura do ar</th>
       </tr>
    </thead>

    <tbody>
      <% @measurements.each_with_index do |measurement, index| %>
        <tr>
          <td><%= measurement.gathering_time.to_formatted_s(:time) %></td>
          <td><%= measurement.gathering_date %></td>
          <td><%= measurement.latitude %></td>
          <td><%= measurement.longitude %></td>
          <td><%= measurement.absolute_humidity %></td>
          <td><%= measurement.air_humidity %></td>
          <td><%= measurement.air_temperature %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <div id="botao">
    <%= link_to "Voltar", measurements_path, class: 'btn btn-default' %>
  </div>

</html>